// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkomU4Tax4vjgnHec9PxalKxtnuP0_qlU',
    appId: '1:330180559764:web:a4823ae3cabc733a9fc581',
    messagingSenderId: '330180559764',
    projectId: 'impulsetrade-75c44',
    authDomain: 'impulsetrade-75c44.firebaseapp.com',
    storageBucket: 'impulsetrade-75c44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOcbXKeM0iqzwOfnKlLqjwkWlvtUk1-nE',
    appId: '1:330180559764:android:5f84c8dac41d999c9fc581',
    messagingSenderId: '330180559764',
    projectId: 'impulsetrade-75c44',
    storageBucket: 'impulsetrade-75c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClYc-TIITgRq1TRYna7_hhsmC2rwoQtU4',
    appId: '1:330180559764:ios:de9d73cf1591ac9f9fc581',
    messagingSenderId: '330180559764',
    projectId: 'impulsetrade-75c44',
    storageBucket: 'impulsetrade-75c44.firebasestorage.app',
    iosBundleId: 'com.example.impulsetrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClYc-TIITgRq1TRYna7_hhsmC2rwoQtU4',
    appId: '1:330180559764:ios:de9d73cf1591ac9f9fc581',
    messagingSenderId: '330180559764',
    projectId: 'impulsetrade-75c44',
    storageBucket: 'impulsetrade-75c44.firebasestorage.app',
    iosBundleId: 'com.example.impulsetrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkomU4Tax4vjgnHec9PxalKxtnuP0_qlU',
    appId: '1:330180559764:web:219f7945624d159c9fc581',
    messagingSenderId: '330180559764',
    projectId: 'impulsetrade-75c44',
    authDomain: 'impulsetrade-75c44.firebaseapp.com',
    storageBucket: 'impulsetrade-75c44.firebasestorage.app',
  );
}
